class_name data

const shop_types = [
	"Potion components",
	"Colouratives",
	"Purifiers",
	"Oils",
	"Medicines",
	"Metals and Alloys",
	"Devices",
	"Hand implements",
	"Advanced implements",
	"Medical Implements",
	"Artefacts of Fire and Ice",
	"Translocationaries",
	"Armaments",
	"Precious metals and gemstones",
	"Musical Instruments",
	"Tomes",
	"Flexibles",
	"Skinworks",
	"Building Materials",
	"Furnishings",
	"Utensils",
	"Bindings",
	"Threads",
	"Textiles",
	"Clothing",
	"Lace and Embroidery",
	"Carpets",
	"Playthings",
	"Food",
	"Drinks",
]

const customer_names = [
	"Aloha Bitterfig",
	"Magpie Twistyhorn",
	"Blaze Limecup",
	"Badger Coppermello",
	"Sprinkles Beautycreek",
	"Mulberry Catcliff",
	"Raine Carrotglimmer",
	"Aodh Beautyswamp",
	"Aeden Snowcurl",
	"Tiger Daywhite",
	"Tangy Elmgrace",
	"Barley Frozenwink",
	"Twig Limefall",
	"Blaze Winterray",
	"Barley Sandylashes",
	"Moonbeam Islecloud",
	"Pistachio Citrusnut",
	"Luke Graydust",
	"Tarragon Broomwhisk",
	"Sprinkles Cutetwirls",
	"Infinity Lilydove",
	"Nora Icemint",
	"Marceline Seabeam",
	"Diamond Mapledew",
	"Sprinkles Poplarfruit",
	"Hydrangea Seatail",
	"Amy Rainbowwink",
	"Pine Plumfruit",
	"Pandora Olivemint",
	"Daffodil Greyvine",
	"Juniper Littlebutton",
	"Marina Seadew",
	"Poison Figboots",
	"Mossy Fernbush",
	"Jasmine Glitterroot",
	"Ezra Icespeck",
	"Marigold Foggyfly",
	"Heather Diamondgrace",
	"Clover Lightningcliff",
	"Sunlight Purplerock",
]

static func name() -> String:
	return util.pick(customer_names)
