class_name data

const shop_types = [
	"Potion components",
	"Colouratives",
	"Purifiers",
	"Oils",
	"Medicines",
	"Metals and Alloys",
	"Devices",
	"Hand implements",
	"Advanced implements",
	"Medical Implements",
	"Artefacts of Fire and Ice",
	"Translocationaries",
	"Armaments",
	"Precious metals and gemstones",
	"Musical Instruments",
	"Tomes",
	"Flexibles",
	"Skinworks",
	"Building Materials",
	"Furnishings",
	"Utensils",
	"Bindings",
	"Threads",
	"Textiles",
	"Clothing",
	"Lace and Embroidery",
	"Carpets",
	"Playthings",
	"Food",
	"Drinks",
]

const customer_names = [
	"Aloha Bitterfig",
	"Magpie Twistyhorn",
	"Blaze Limecup",
	"Badger Coppermello",
	"Sprinkles Beautycreek",
	"Mulberry Catcliff",
	"Raine Carrotglimmer",
	"Aodh Beautyswamp",
	"Aeden Snowcurl",
	"Tiger Daywhite",
	"Tangy Elmgrace",
	"Barley Frozenwink",
	"Twig Limefall",
	"Blaze Winterray",
	"Barley Sandylashes",
	"Moonbeam Islecloud",
	"Pistachio Citrusnut",
	"Luke Graydust",
	"Tarragon Broomwhisk",
	"Sprinkles Cutetwirls",
	"Infinity Lilydove",
	"Nora Icemint",
	"Marceline Seabeam",
	"Diamond Mapledew",
	"Sprinkles Poplarfruit",
	"Hydrangea Seatail",
	"Amy Rainbowwink",
	"Pine Plumfruit",
	"Pandora Olivemint",
	"Daffodil Greyvine",
	"Juniper Littlebutton",
	"Marina Seadew",
	"Poison Figboots",
	"Mossy Fernbush",
	"Jasmine Glitterroot",
	"Ezra Icespeck",
	"Marigold Foggyfly",
	"Heather Diamondgrace",
	"Clover Lightningcliff",
	"Sunlight Purplerock",
]

const associated_shops = {
	'Potion components': ['Purifiers', 'Oils', 'Advanced implements', 'Tomes'],
	'Colouratives': ['Skinworks', 'Textiles', 'Clothing', 'Carpets'],
	'Purifiers': ['Potion components', 'Clothing', 'Food', 'Drinks'],
	'Oils': ['Potion components', 'Metals and Alloys', 'Artefacts of Fire and Ice', 'Food'],
	'Medicines': ['Advanced implements', 'Medical Implements', 'Tomes', 'Utensils'],
	'Metals and Alloys': ['Oils', 'Hand implements', 'Armaments', 'Building Materials'],
	'Devices': ['Translocationaries', 'Musical Instruments', 'Furnishings', 'Lace and Embroidery'],
	'Hand implements': ['Metals and Alloys', 'Artefacts of Fire and Ice', 'Precious metals and gemstones', 'Bindings'],
	'Advanced implements': ['Potion components', 'Medicines', 'Precious metals and gemstones', 'Threads'],
	'Medical Implements': ['Medicines', 'Tomes', 'Skinworks', 'Textiles'],
	'Artefacts of Fire and Ice': ['Oils', 'Hand implements', 'Translocationaries', 'Food'],
	'Translocationaries': ['Devices', 'Artefacts of Fire and Ice', 'Flexibles', 'Bindings'],
	'Armaments': ['Metals and Alloys', 'Flexibles', 'Building Materials', 'Clothing'],
	'Precious metals and gemstones': ['Hand implements', 'Advanced implements', 'Musical Instruments', 'Lace and Embroidery'],
	'Musical Instruments': ['Devices', 'Precious metals and gemstones', 'Tomes', 'Playthings'],
	'Tomes': ['Potion components', 'Medicines', 'Medical Implements', 'Musical Instruments'],
	'Flexibles': ['Translocationaries', 'Armaments', 'Building Materials', 'Playthings'],
	'Skinworks': ['Colouratives', 'Medical Implements', 'Furnishings', 'Textiles'],
	'Building Materials': ['Metals and Alloys', 'Armaments', 'Flexibles', 'Carpets'],
	'Furnishings': ['Devices', 'Skinworks', 'Lace and Embroidery', 'Carpets'],
	'Utensils': ['Medicines', 'Bindings', 'Threads', 'Drinks'],
	'Bindings': ['Hand implements', 'Translocationaries', 'Utensils', 'Playthings'],
	'Threads': ['Advanced implements', 'Utensils', 'Lace and Embroidery', 'Carpets'],
	'Textiles': ['Colouratives', 'Medical Implements', 'Skinworks', 'Clothing'],
	'Clothing': ['Colouratives', 'Purifiers', 'Armaments', 'Textiles'],
	'Lace and Embroidery': ['Devices', 'Precious metals and gemstones', 'Furnishings', 'Threads'],
	'Carpets': ['Colouratives', 'Building Materials', 'Furnishings', 'Threads'],
	'Playthings': ['Musical Instruments', 'Flexibles', 'Bindings', 'Drinks'],
	'Food': ['Purifiers', 'Oils', 'Artefacts of Fire and Ice', 'Drinks'],
	'Drinks': ['Purifiers', 'Utensils', 'Playthings', 'Food'],
}

const shop_names = [
	"The Ectoplasm",
	"The Silver Spoon",
	"Hell's Gate",
	"The Banished Beast",
	"Runes and Rods",
	"The Amazing Talisman",
	"The Bitter Chupacabra",
	"The Early Griffin",
	"The Brown Fairy",
	"The Common Elemental",
	"la Rune",
	"Runes Radicales",
	"Invisibilité et Invincibilité",
	"Envoûté",
	"Point de Rupture",
	"le Chaudron Vilain",
	"le Rouleau Poilu",
	"le Cyclope Seul",
	"le Cupidon Câlin",
	"la Rune Célèbre",
	"The Bloodstone",
	"The Holy Grail",
	"The Sword in the Stone",
	"The White Dove",
	"The Revelation",
	"The Dizzy Feathered Serpent",
	"The Huge Angel",
	"The Bronze Staff",
	"The Crazy Shield",
	"The Cheering Sphinx",
	"The Philosopher's Stone",
	"The Sphere",
	"Orbs and Talismans",
	"Bona Fide",
	"The Red Slippers",
	"The Scary Elf",
	"The Flimsy Roc",
	"The Brass Dragon",
	"The Light Book",
	"The Fluffy Book",
]

static func get_shopbg_type():
	return shop_types[randi() % 14]
static func get_shop_type():
	return util.pick(shop_types)
static func name() -> String:
	return util.pick(customer_names)
static func shop_name() -> String:
	return util.pick(shop_names)
